services:
  - type: web
    name: personeros-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --worker-class gthread --threads 4 --timeout 120 --graceful-timeout 30
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
